version: '3.8'

services:
  db:
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:16.1-bullseye
    expose:
      - 5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h db -p 5432 -U ${POSTGRES_USER}"
        ]

  api:
    restart: on-failure
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    command: "java -jar api/build/libs/huinya-api.jar"
    links:
      - db
    ports:
      - "8085:8085"

  bot:
    restart: on-failure
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/bot.dockerfile
    command: "java -jar bot/build/libs/huinya-bot.jar"
    links:
      - db

  web:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    command: "npm start"
    env_file:
      - .env
    ports:
      - "3000:3000"